repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=10800']

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.2
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: ['dbt-postgres']
      - id: sqlfluff-fix
        args: ['--FIX-EVEN-UNPARSABLE'] # by default fluff doesn't fix files with PRS or TMP issues this allows it to
        additional_dependencies: ['dbt-postgres']